export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  CERTIFICATION_CREATE = 'CERTIFICATION_CREATE',
  CERTIFICATION_UPDATE = 'CERTIFICATION_UPDATE',
  CERTIFICATION_DELETE = 'CERTIFICATION_DELETE',
  FRAMEWORK_CREATE = 'FRAMEWORK_CREATE',
  FRAMEWORK_UPDATE = 'FRAMEWORK_UPDATE',
  FRAMEWORK_DELETE = 'FRAMEWORK_DELETE',
  UPLOAD_CREATE = 'UPLOAD_CREATE',
  UPLOAD_DELETE = 'UPLOAD_DELETE',
  REPORT_GENERATE = 'REPORT_GENERATE',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
  SECURITY_EVENT = 'SECURITY_EVENT',
  DATA_EXPORT = 'DATA_EXPORT',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}

export enum AuditSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export class CreateAuditLogDto {
  action: AuditAction;
  severity: AuditSeverity;
  description: string;
  userId?: string;
  organizationId: string;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, any>;
}
